name: notesapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.0.1
  firebase_database: ^9.0.20
  firebase_core: ^1.20.0
  flutter_animated_dialog: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
     - family: Graduate
       fonts:
         - asset: fonts/Graduate-Regular.ttf
     - family: Itim
       fonts:
         - asset: fonts/Itim-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
